import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar/Navbar";
import Footer from "../components/footer/Footer"
import ClientOnly from "../components/ClinetOnly";
import RegisterModal from "../components/Modals/RegisterModal";
import LoginModal from "../components/Modals/LoginModal";
import ToasterProvider from "./providers/ToasterProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MyTutor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="container">
      <ClientOnly>
      <ToasterProvider/>
      <Navbar/>  
      <LoginModal/>
      <RegisterModal/>
      </ClientOnly>  
      {children}
      <Footer/>
      </div>
      </body>
    </html>
  );
}
